#!/bin/bash

if [ "$#" -ne "2" ]
then
	echo "Exactly 2 arguments are required, action type <archive, deprecate> <patch-name>
fi


if [ ! "$1" = "archived" ] && [ ! "$1" = "deprecated" ]
then
	echo "Please specify either archived or deprecated as the action type"
fi

_patch_name=$(basename $2 | sed -e "s/\\.patch$//")
_has_dependencies=0
for f in $(find patches -type f | grep \\.patch/dependencies$)
do
	_count=$(grep -c $_patch_name $f)
	if [ "$_count" -gt "0" ]
	then
		echo "dependency:$f"
		((_has_dependencies++)
	fi
done

if [ "$_has_dependencies" -gt "0" ]
then
	echo "This patch has at least 1 other dependency:$f"
	exit 1
fi

# archive / deprecate the patch
mkdir -p $1
mv $2 $1
