#!/bin/bash

#i=0

# ensure all run scripts are executable
for patch_hook in $(find patches/ -type d| grep hooks/pre-commit$)
do
	for hook_script in $(find $patch_hook -type l && find $patch_hook -type f)
	do
		#echo -e "running pre-commit hook ($i): $hook_script"
		
		_patch=$(echo -e $patch_hook | grep -Po "^.*\\.patch")
		
		# execute the hook script
		$hook_script $_patch
		
		#((i++))
	done
done
